Add top variable to limit the maximum annual flow of tokens per vest
makerdao/dss-vest pull request #23
Opened 2021-05-18 15:53 UTC by brianmcmichael

Rate limit the maximum amount of tokens that can be issued per year, per vest

2021-05-18 16:07 UTC, hexonaut requested changes
Overall looks good, but one requested change to the units, and a typo.

2021-05-18 16:07 UTC, hexonaut commented on src/DssVest.sol
> +        else revert("Clipper/file-unrecognized-param");
Should be `else revert("DssVest/file-unrecognized-param");`

2021-05-18 16:07 UTC, hexonaut commented on src/DssVest.sol
> +        require(_tot / _tau * ONE_YEAR <= top,             "DssVest/tot-too-high");
I think I would prefer to see this in the natural units of amount / second. The top parameter can be succinctly represented as `500 * WAD / 365 days` to do the conversion easily.

2021-05-18 16:12 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau * ONE_YEAR <= top,             "DssVest/tot-too-high");
makes sense. see change at 51bb4ae729d95c20204911529f58d86433b28b26

2021-05-18 16:35 UTC, hexonaut requested changes

2021-05-18 16:35 UTC, hexonaut commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
Sorry I meant I think it will be cleaner to remove the arbitrary time unit altogether and specify something like `500 * WAD / 365 day` in the calling function instead of `500 * WAD`. DssVest.t.sol in this case.

2021-05-18 17:00 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
I'm not sure that will be an easier value for governance to manage.

2021-05-18 17:02 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
Here we provide a single maximum amount that governance is willing to pay out per year, per vest. I think it makes more sense to specify that than to make them do the calculation we're doing here outside of the contract.

2021-05-18 17:10 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
ok, maybe it does make sense to do it that way. I do think this will be harder to reason about when looking at it from the outside.

2021-05-18 17:38 UTC, hexonaut commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
Personally, I think writing `500 * WAD / 365 days` is a very clear description of 500 MKR / year.

2021-05-18 18:06 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
Opened a new PR at https://github.com/makerdao/dss-vest/pull/25/files to discuss.

2021-05-18 20:24 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
> Personally, I think writing 500 * WAD / 365 days is a very clear description of 500 MKR / year.

Consider that you will be deploying this with seth, where that formula will not be clear to an end user, and that this variable will be exposed publically as: `15854895991882`

2021-05-19 11:28 UTC, hexonaut commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
There isn't really anywhere else in the code though where it is not in seconds for the time unit. To me it's more intuitive to always use natural units which in this case is wads / second - even if it is slightly awkward for the deploy.

2021-05-19 18:17 UTC, gbalabasquer commented on src/fuzz/DssVestEchidnaTest.sol
> +        usr;
If `usr` is not being used, it can be just removed from the left side, like the same the last value which is not being used.

2021-05-19 18:23 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
I'm fine with either option. I see putting a value per year is easier to reason about, but at the same time we do every `rate` at seconds basis on the code. I guess `DssExecLib` could handle the conversion if we want to do it per year at spell level.

2021-05-19 18:32 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(_tot / _tau <= top / 365 days,             "DssVest/tot-too-high");
So thinking it a bit more, I think I'd prefer the per second option.

2021-05-26 12:13 UTC, hexonaut requested changes
Minor change then I think this is good to go.

2021-05-26 12:13 UTC, hexonaut commented on src/DssVest.sol
> +        require(_tot / _tau <= cap,                        "DssVest/tot-too-high");
This should say `"DssVest/rate-too-high"` imo.

2021-05-26 13:10 UTC, gbalabasquer commented on src/fuzz/DssVestEchidnaTest.sol
> +        usr;
Changed.

2021-05-26 13:10 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(_tot / _tau <= cap,                        "DssVest/tot-too-high");
Changed

2021-05-26 13:11 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(_tot / _tau * ONE_YEAR <= top,             "DssVest/tot-too-high");
This was already merged.

2021-05-27 12:28 UTC, hexonaut approved these changes
LGTM 👍  Tests passing.

2021-05-27 12:29 UTC, merged