Permissionless vest, with the option to restrict
makerdao/dss-vest pull request #29
Opened 2021-06-30 16:02 UTC by brianmcmichael

Changes the default vesting function to be permissionless, but adds the option to restrict or unrestrict a contract so that it can only be vested by the owner.

2021-07-01 11:00 UTC, hexonaut requested changes
LGTM after small visibility change.

2021-07-01 11:00 UTC, hexonaut commented on src/DssVest.sol
> +    function restrict(uint256 _id) public {
Can be `external`. Same for `unrestrict`.

2021-07-01 13:00 UTC, gbalabasquer commented on src/DssVest.sol
> +        }
```suggestion
        require(restricted[_id] == 0 || _award.usr == msg.sender, "DssVest/only-user-can-claim");
```

2021-07-01 13:23 UTC, gbalabasquer commented on src/DssVest.t.sol
> +    function testRestrict() public {
This merged test should also include a call to `vest` from the owner when it is restricted to test that condition.

2021-07-01 20:17 UTC, brianmcmichael commented on src/DssVest.t.sol
> +    function testRestrict() public {
done

2021-07-01 20:40 UTC, brianmcmichael commented on src/DssVest.sol
> +    function restrict(uint256 _id) public {
done

2021-07-01 20:57 UTC, gbalabasquer approved these changes
LGTM

2021-07-03 13:00 UTC, hexonaut approved these changes
LGTM

2021-07-04 16:18 UTC, merged