Add DssVest Specs
makerdao/dss-vest pull request #32
Opened 2021-07-07 22:44 UTC by naszam

2021-07-15 08:11 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    assert(revert1 => lastReverted, "Lack of auth did not revert");
it's not a problem here, but I'd make it a habit to extract `lastReverted` to a variable right after calling the function under inspection

2021-07-15 08:13 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    assert(cap(e) == data, "File did not set cap as expected");
do `file`, `cap` need the environment? if yes, maybe use two different environments for more generality.
if not, maybe declare those as `envfree`

2021-07-15 08:15 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    uint256 _ids = ids(e);
the less `env` reuse the better - here perhaps only `init` needs it?

2021-07-15 08:17 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    uint256 WAD = 10^18;
you could use a definition `definition WAD() returns uint256 = 10^18;` that is available to all rules and behaves like a macro

2021-07-15 08:19 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    require(rxd <= tot);
do you think it makes sense to write a rule such as:
```
rule inv_awards(uint id, method f) {
  usr, bgn, clf, fin, tot, rxd, mgr = awards(id);
  // the above require block
  env e; 
  calldataarg arg;
  f(e, arg);

  // the above requires, but with assert instead!
}
```

2021-07-15 08:24 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    //TODO authority.canCall(src, address(this), sig) return false
this is clearer now - you can make a mock authority, add a `using MockAuthority as authorityInstance`,
add:
```
bool revertN = authorityInstance.canCall(...)
```
and in `methods` section:
```
  canCall(..) returns bool => DISPATCHER(true) UNRESOLVED
```

2021-07-15 08:26 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    require(fin > bgn);
so this is the same require as in `vest` so if you proved it with a rule as I explained above, this require becomes much safer.
Also if you proceed to use ghosts + invariant (or maybe you have individual getters for each component returned by `awards`, but if not you can use ghosts), then you can `requireInvariant` here instead

2021-07-15 08:32 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    uint256 max_uint48 = 2^48 - 1;
until we add this as a keyword maybe use a `definition` to avoid redefining it in many rules

2021-07-15 14:11 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    assert(cap(e) == data, "File did not set cap as expected");
Done. I've declared `wards`, `ids` and `cap` `envfree`.
I'm not sure why we should define `file` `envfree` as well as is an external function we want to verify.

2021-07-15 14:12 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    uint256 _ids = ids(e);
Done.

2021-07-15 14:42 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    uint256 WAD = 10^18;
Done.

2021-07-15 17:02 UTC, gbalabasquer commented on src/specs/DssVestMintable.spec
> +    require(rxd <= tot);
Hmm I'm not really sure this will work.
We still need to check the `pre` values between each other. Shouldn't happen the same with the other rules that we will have counter examples where `pre_bgn > pre_fin` due the random initial state? When that's actually not feasible via the smart contract flow...
I think we should have to tell the prover that those values are initialized to 0 and then write an invariant where `fin > bgn`. Then that invariant could be required in the `vest` rule.

2021-07-15 19:27 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    //TODO authority.canCall(src, address(this), sig) return false
Done. Let me know what do you think!

2021-07-24 19:52 UTC, shellygr commented on src/specs/DssVestMintable.spec
> +    require(rxd <= tot);
but in the rule above it's suggested that you do take the require on the pre values as in the `vest` rule - so `pre_bgn > pre_fin` wouldn't be possible

2021-07-27 21:23 UTC, kmbarry1 commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
Don't you need a `require(token == gem());` like in the proof below?

2021-08-06 19:48 UTC, naszam commented
* `DssVestMintable`
```
certoraRun src/DssVest.sol:DssVestMintable src/specs/DSToken.sol src/specs/MockAuthority.sol --link DssVestMintable:gem=DSToken DSToken:authority=MockAuthority --verify DssVestMintable:src/specs/DssVestMintable.spec --optimistic_loop --rule_sanity
```
[Report](https://prover.certora.com/output/42696/be2236c7df6a044e696f?anonymousKey=a0c42569fb8bf20fafef75c49bd81e1dcd601329)

* `DssVestSuckable`
```
certoraRun src/DssVest.sol:DssVestSuckable src/specs/ChainLog.sol src/specs/Vat.sol src/specs/DaiJoin.sol src/specs/Dai.sol --link DssVestSuckable:chainlog=ChainLog DssVestSuckable:vat=Vat DssVestSuckable:daiJoin=DaiJoin DaiJoin:vat=Vat DaiJoin:dai=Dai --verify DssVestSuckable:src/specs/DssVestSuckable.spec --optimistic_loop --rule_sanity
```
[Report](https://prover.certora.com/output/42696/c18a1e3db95cf85a7d3b?anonymousKey=a12a73f0432ec48500f23ba5f286f4c818adcd9e)

* `DssVestTransferrable`
```
certoraRun src/DssVest.sol:DssVestTransferrable src/specs/Dai.sol --link DssVestTransferrable:gem=Dai --verify DssVestTransferrable:src/specs/DssVestTransferrable.spec --optimistic_loop --rule_sanity
```
[Report](https://prover.certora.com/output/42696/7c2612833c753f765627?anonymousKey=7f97af03c88c9ee93bf90d592e9698777ca61c40)

2021-08-11 16:16 UTC, hexonaut requested changes
I've listed my comments against the `DssVestMintable` spec, but they should be applied to all 3 variants.

2021-08-11 16:16 UTC, hexonaut commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp < bgn => bgn2 == e.block.timestamp, "Yank did not set bgn as expected when block timestamp is less than bgn");
`e.block.timestamp < bgn` already implies `e.block.timestamp < fin` so this can be relaxed to just `e.block.timestamp < bgn` I think.

2021-08-11 16:16 UTC, hexonaut commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp < clf => tot2 == 0, "Yank did not set tot as expected when block timestamp is less than clf");
Similar with all of these. `e.block.timestamp < fin` can be dropped.

2021-08-11 16:16 UTC, hexonaut commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp >= bgn && e.block.timestamp >= clf => tot2 == unpaidAmt + rxd, "Yank did not set tot as expected");
I think this is missing asserts where `e.block.timestamp >= fin`.

2021-08-11 16:16 UTC, hexonaut commented on src/specs/DssVestMintable.spec
> +    assert(_end2 < fin && _end2 >= bgn && _end2 >= clf => tot2 == unpaidAmt + rxd, "Yank did not set tot as expected");
Similar for here as `yank` rule.

2021-08-12 14:10 UTC, gbalabasquer commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
This is actually a good question, I still do not understand well why in certain cases we need to do the binding in the rule when it is already linked in the command. Originally the `require` that we needed about this was `vest_revert` having to put `require(authority == token.authority());` to make it work. I think I added the token one without actually needing it.
This is something we should discuss in more deep with Shelly.

2021-08-12 15:04 UTC, gbalabasquer commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp < bgn => bgn2 == e.block.timestamp, "Yank did not set bgn as expected when block timestamp is less than bgn");
Changed.

2021-08-12 15:04 UTC, gbalabasquer commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp < clf => tot2 == 0, "Yank did not set tot as expected when block timestamp is less than clf");
Changed.

2021-08-12 15:19 UTC, gbalabasquer commented on src/specs/DssVestMintable.spec
> +    assert(e.block.timestamp < fin && e.block.timestamp >= bgn && e.block.timestamp >= clf => tot2 == unpaidAmt + rxd, "Yank did not set tot as expected");
Done.

2021-08-12 16:33 UTC, hexonaut approved these changes
LGTM all 3 specs passing tests

2021-08-17 17:12 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +methods {
`file` is not in here even though it is used below in specs...not sure why there isn't an error, but should probably be added here for completeness.

2021-08-17 17:15 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +methods {
Actually same goes for a number of other functions: `rely`, `deny`, `create`, `vest`, `accrued`, `unpaid`, `restrict`, `unrestrict`, `yank`, `move`, `pay`.

2021-08-17 17:26 UTC, naszam commented on certora/DssVestSuckable.spec
> +methods {
We declared in `methods` `envfree` functions, that don't require `env`.
I've just double checked the reports above and the invariants should cover all the dss-vest functions.
Also double checked the [docs](https://certora.atlassian.net/wiki/spaces/CPD/pages/181960777/Method+Declarations) and it seems that's required only if the function implementation is not in the verification context.
@gbalabasquer any thoughts on this?

2021-08-17 17:28 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +invariant everythingNotSetIfUsrNotSet(uint256 _id) usr(_id) == 0 => bgn(_id) == 0 && clf(_id) == 0 && fin(_id) == 0 && tot(_id) == 0 && rxd(_id) == 0 && mgr(_id) == 0 && res(_id) == 0
nit: I would order the RHS of the implication so the values are in the same order as they are in the struct.

2021-08-17 17:28 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +methods {
Also, nit: I would put the functions in the same order as they appear in the contract.

2021-08-17 18:30 UTC, thomasbernardi commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
Import statements basically creates contract instances. You could import several `DSToken`s, for example token1, token2. These each get separate static addresses.

The linking in the run command tells the tool how to resolve functions for calls on that storage slot, but allows the contract instance (i.e. address stored in the slot) to be _anything_. The require makes sure that the two are the _same_ instance.

2021-08-17 18:39 UTC, kmbarry1 commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
Recommendation from the Certora team is to include the `require`, because it's need to connect the symbolic link to a concrete address, which is only assigned during proving.

2021-08-17 18:43 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +methods {
Okay after talking with Certora, sounds like there is no need to add functions that are not `envfree` here, so let's not do it.

2021-08-17 18:43 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +methods {
I still recommend contract-ordering these, btw.

2021-08-17 18:45 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
Addressed with Shelly and Thomas.
We should use the require when the storage variable is used as it helps the tool to link external contracts and it's actually a required step to link contracts on top of the command linking.

2021-08-17 18:51 UTC, naszam commented on certora/DssVestSuckable.spec
> +methods {
Addressed with Shelly and Thomas.
We should add in `methods` only the functions that we assign a specific behaviour, like `envfree` or associated with a [*summary*](https://certora.atlassian.net/wiki/spaces/CPD/pages/41058462/Function+Summarization#Calls-inside-the-code) like `DISPATCHER`, ...

2021-08-17 19:31 UTC, naszam commented on certora/DssVestSuckable.spec
> +methods {
Done for mintable specs.
@kmbarry1 let me know if that's ok and I'll push for the other specs.

2021-08-17 19:36 UTC, kmbarry1 commented on certora/DssVestMintable.spec
> +    gem() returns (address) envfree
I think this was actually in the right place before--functions of the inherited contract should precede those of the inheriting contract.

2021-08-17 19:42 UTC, naszam commented on certora/DssVestMintable.spec
> +    gem() returns (address) envfree
Done.

2021-08-17 20:55 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +// }
Can this be removed? Looks like it is an alternative attempt at expressing the rule below, which seems more general.

2021-08-17 20:57 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(wards(usr) == 1, "Rely did not set the wards as expected");
nit: when something is a function name, I would not capitalize it in an error message (so would use "rely" instead of "Rely" here)

2021-08-17 20:57 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(wards(usr) == 0, "Deny did not set the wards as expected");
nit: when something is a function name, I would not capitalize it in an error message (so would use "rely" instead of "Rely" here)

2021-08-17 20:59 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(_rxd == rxd_, "Rxd did not return the award rxd as expected");
Same thing here with not capitalizing function names in failure messages.

2021-08-17 21:04 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +rule award(uint256 _id) {
We don't check revert conditions for these (which should be only if `msg.value > 0`)...that's probably fine, although maybe it would be nice to confirm that indeed only the single revert case we expect exists?

2021-08-17 21:08 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
How are we deciding when to wrap lines? E.g. line 194 is actually shorter than line 192. If it's just based on aesthetics, IMO having then entire logical expression on a single line is the way to go:

```
    assert(lastReverted => revert1 || revert2 || revert3 || revert4,
                                    "Revert rules are not covering all the cases");
```

2021-08-17 21:30 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    TWENTY_YEARS() returns (uint256) envfree
There should be a spec confirming that `TWENTY_YEARS` actually returns, well, twenty years in seconds :).

2021-08-17 21:37 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(revert18 => lastReverted, "Tot toUint128 cast overflow did not revert");
Maybe this was already discussed, but IMO the spec is more readable if the `assert` statements are placed immediately below the `bool` declarations, e.g.:

```
bool revert1 = ...
assert(revert1 => lastReverted, "...

bool revert2 = ...
assert(revert2 => lastReverted, "...

...
```

2021-08-17 22:35 UTC, naszam commented on certora/DssVestSuckable.spec
> +methods {
Done.

2021-08-17 22:53 UTC, naszam commented on certora/DssVestSuckable.spec
> +invariant everythingNotSetIfUsrNotSet(uint256 _id) usr(_id) == 0 => bgn(_id) == 0 && clf(_id) == 0 && fin(_id) == 0 && tot(_id) == 0 && rxd(_id) == 0 && mgr(_id) == 0 && res(_id) == 0
Done.

2021-08-18 17:33 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
Looks like this line could be removed since this property is covered by the invariant `rxdLessOrEqualTot`. Alternatively, you could uncomment it and put prior to the `vest` call `require(rxd <= tot);`. Your choice--either one is fine, but let's not leave random commented-out lines lying around.

2021-08-18 19:16 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
Similar story with this line--you can either remove it, or uncomment it and add a sufficient `require` above. Although you'll need a different `require` than the first statement, one you don't already have an invariant for.

2021-08-18 19:20 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    uint256 balanceBefore = dai.balanceOf(usr);
This is another interesting case like we discussed in the call where we didn't need `require(daiJoin.dai() == dai);` and it still passes. My understanding though was that this in general isn't safe and we should probably add the `require` just to be on the safe side rather than relying on the linkage (and it's more self-documenting as well).

2021-08-18 19:54 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    uint256 balanceBefore = dai.balanceOf(usr);
Probably want the `vat` `require` as well.

2021-08-18 20:07 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    bool revert5  = e.block.timestamp >= clf && e.block.timestamp >= bgn && e.block.timestamp < fin && tot * (e.block.timestamp - bgn) > max_uint256;
I wonder it these math expressions are really behaving the way we think they are. All the local variables have been declared with EVM-corresponding types, which means that EVM arithmetic will be applied by default:

https://certora.atlassian.net/wiki/spaces/CPD/pages/7340101/Types#EVM-types-vs.-mathematical-types

Although possibly when they are used in `assert` statements the mathematical operators are used instead of EVM ones (since internally the tool must be remembering the expression on these assignments). Have we checked with the Certora folks about this?

2021-08-18 21:37 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +// Verify that awards behaves correctly on vest with arbitrary max amt
```suggestion
// Verify that awards behave correctly on vest with arbitrary max amt
```

2021-08-18 21:54 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
Same thing here regarding commented-out lines.

2021-08-18 21:54 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
Same thing here regarding commented-out lines.

2021-08-19 14:03 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(wards(usr) == 1, "Rely did not set the wards as expected");
Done.

2021-08-19 14:03 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(wards(usr) == 0, "Deny did not set the wards as expected");
Done.

2021-08-19 14:03 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(_rxd == rxd_, "Rxd did not return the award rxd as expected");
Done.

2021-08-19 14:32 UTC, naszam commented on certora/DssVestSuckable.spec
> +// Verify that awards behaves correctly on vest with arbitrary max amt
I've fixed `behave` in all the spec comments.
Done.

2021-08-19 14:58 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +// Verify that awards behaves correctly on vest with arbitrary max amt
well is `awards` variable, so IMO is `behaves`. But yeah this case can be confusing, shouldn't be change for singular variable names for sure.

2021-08-20 12:30 UTC, naszam commented on certora/DssVestSuckable.spec
> +rule award(uint256 _id) {
As per `valid` spec, we could add the revert case to confirm that all revert cases are covered but this won't include the `msg.value > 0` cause the award getters are declared `envfree` in methods and that revert case is already being checked by the tool as you can see in the report, in the section `envfreeFuncsAreNonpayable`.

2021-08-20 12:38 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +rule award(uint256 _id) {
Ah didn't realize that `envfree` basically covers this automatically, nice.

2021-08-20 12:54 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +            revert4, "Revert rules are not covering all the cases");
Similar formatting nit here--putting splitting up the logical expression like this isn't particularly readable. Consider e.g.
```
    assert(lastReverted => revert1 || revert2 || revert3 || revert4, 
           "Revert rules are not covering all the cases");
```

2021-08-20 12:55 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    uint256 accruedAmt =
naming nit: I'd call this `expectedAmt` or something similar

2021-08-20 12:55 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    uint256 accruedAmt =
naming nit: I'd call this `expectedAmt` or something similar

2021-08-20 12:59 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +            revert4 || revert5, "Revert rules are not covering all the cases");
Same formatting nit here--would prefer to keep the logical expression together, and also not put the error message on the same line as the logical expression.

2021-08-20 13:00 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +// Verify that restricted behaves correctly on restrict
Maybe say `res` instead of `restricted`.

2021-08-20 13:00 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(res(_id) == 1, "restrict did not set restricted as expected");
ditto

2021-08-20 13:02 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +// Verify that restricted behaves correctly on unrestrict
Again--say `res` instead of `restricted`?

2021-08-20 13:02 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(res(_id) == 0, "restrict did not set restricted as expected");
ditto

2021-08-20 13:16 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(e.block.timestamp >= fin => tot2 == tot && clf2 == clf && bgn2 == bgn, "yank did not keep tot, clf and bgn the same as expected");
Should add `&& fin2 == fin` to the RHS of the implication.

2021-08-20 13:18 UTC, naszam commented on certora/DssVestSuckable.spec
> +// Verify that restricted behaves correctly on restrict
Done.

2021-08-20 13:18 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(res(_id) == 1, "restrict did not set restricted as expected");
Done.

2021-08-20 13:18 UTC, naszam commented on certora/DssVestSuckable.spec
> +// Verify that restricted behaves correctly on unrestrict
Done.

2021-08-20 13:18 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(res(_id) == 0, "restrict did not set restricted as expected");
Done.

2021-08-20 13:22 UTC, naszam commented on certora/DssVestSuckable.spec
> +rule award(uint256 _id) {
Done.

2021-08-20 14:00 UTC, naszam commented on certora/DssVestSuckable.spec
> +    bool revert5  = e.block.timestamp >= clf && e.block.timestamp >= bgn && e.block.timestamp < fin && tot * (e.block.timestamp - bgn) > max_uint256;
Yeah, we should double check with Shelly

2021-08-20 16:45 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
`Fin` --> `fin`

2021-08-20 16:46 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(_end2 >= fin => tot2 == tot && clf2 == clf && bgn2 == bgn, "yank did not keep tot, clf and bgn the same as expected");
Should add `&& fin2 == fin` to the RHS of the implication. (And update the message, of course.)

2021-08-20 16:49 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
`Fin` --> `fin`

2021-08-20 16:49 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
formatting

2021-08-20 16:52 UTC, kmbarry1 commented
I've now completed a full pass on DssVestSuckable.spec. Once all comments are resolved and I've checked the changes, I'll review the other two large specs using a diff checker to speed things up.

2021-08-23 20:41 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(lastReverted => false, "Revert rules are not covering all the cases");
Don't we actually need to check this after each function call, since it gets overwritten each time?

2021-08-23 20:43 UTC, kmbarry1 commented on certora/DssVestSuckable.spec
> +    assert(lastReverted => false, "Revert rules are not covering all the cases");
Also wouldn't `!lastReverted` be clearer than `lastReverted => false`?

2021-08-25 12:52 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    assert(revert1 => lastReverted, "Lack of auth did not revert");
We could use, instead of `lastReverted`, `<func_name>Reverted` (e.g. `vestReverted`) as best practice as described in the [docs](https://certora.atlassian.net/wiki/spaces/CPD/pages/41124372/Common+Pitfalls#lastReverted-updates).
What do you think @gbalabasquer @kmbarry1?

2021-08-25 13:34 UTC, naszam commented on src/specs/DssVestMintable.spec
> +    uint256 balanceBefore = token.balanceOf(usr);
Done in 7a97789.

2021-08-25 13:44 UTC, naszam commented on certora/DssVestSuckable.spec
> +// }
I think @gbalabasquer would like to keep these attempts to document the approach to define the invariant `rxdLessOrEqualTot`. We could either add comments to explain the approach or move these attempts to another source (e.g. hackmd) to be used for future spec designs.

2021-08-25 13:53 UTC, naszam commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
I've opted to break the line after `revert3` to improve readability but open to consider better alternatives, aesthetics.
cc: @gbalabasquer

2021-08-25 14:22 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(revert18 => lastReverted, "Tot toUint128 cast overflow did not revert");
I would keep it like this as it improves readability and separates variable declarations from assertions IMO.
cc: @gbalabasquer

2021-08-25 14:23 UTC, naszam commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
Same as above.
cc: @gbalabasquer

2021-08-25 14:24 UTC, naszam commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
Same as above.
cc: @gbalabasquer

2021-08-25 14:29 UTC, naszam commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
Same as above.
cc: @gbalabasquer

2021-08-25 14:30 UTC, naszam commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
Same as above.
cc: @gbalabasquer

2021-08-25 14:30 UTC, naszam commented on certora/DssVestSuckable.spec
> +            revert4, "Revert rules are not covering all the cases");
Same as above.
cc: @gbalabasquer

2021-08-25 14:32 UTC, naszam commented on certora/DssVestSuckable.spec
> +    uint256 accruedAmt =
I would keep it like this to avoid confusion between `accruedAmt` and `unpaidAmt`.
cc: @gbalabasquer

2021-08-25 14:33 UTC, naszam commented on certora/DssVestSuckable.spec
> +    uint256 accruedAmt =
Same as above.
cc: @gbalabasquer

2021-08-25 14:33 UTC, naszam commented on certora/DssVestSuckable.spec
> +            revert4 || revert5, "Revert rules are not covering all the cases");
Same as above.
cc: @gbalabasquer

2021-08-25 14:37 UTC, naszam commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
Same as Above.
cc: @gbalabasquer

2021-08-25 14:38 UTC, naszam commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
Same as above.
cc: @gbalabasquer

2021-08-25 15:22 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(e.block.timestamp >= fin => tot2 == tot && clf2 == clf && bgn2 == bgn, "yank did not keep tot, clf and bgn the same as expected");
Done in a854e58.

2021-08-25 15:27 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(_end2 >= fin => tot2 == tot && clf2 == clf && bgn2 == bgn, "yank did not keep tot, clf and bgn the same as expected");
Done in a854e58.

2021-08-25 15:27 UTC, naszam commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
Same as above.

2021-08-25 15:36 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
I think we need to reach consensus on having the error messages starting with or without capitalization otherwise we'll have some message errors starting with capitalization and other without.
cc: @gbalabasquer

2021-08-25 15:36 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
Same as above.

2021-08-25 15:54 UTC, naszam commented on certora/DssVestSuckable.spec
> +    assert(lastReverted => false, "Revert rules are not covering all the cases");
I think this would be better to follow the same pattern as per revert specs, but open for discussion.
cc: @gbalabasquer

2021-08-25 16:03 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
This one is commented because is one which provoked the timeout. We never got a final response on why that was happening.

2021-08-25 16:04 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    // assert(e.block.timestamp >= clf && e.block.timestamp < fin => rxd2 < tot, "rxd should not complete tot before time");
Explained in the prev comment.

2021-08-25 16:07 UTC, gbalabasquer commented on certora/DssVestMintable.spec
> +// Verify that wards behave correctly on rely
I still think it's the `wards` variable (so singular), but if @kmbarry1 thinks this way is the correct one I won't argue with a native speaker.

2021-08-25 16:10 UTC, gbalabasquer commented on certora/DssVestMintable.spec
> +}
This doesn't work as intended as the `lastReverted` gets overwritten in each call. So the only thing you are checking is `rxd` can't revert. The solution to keep everything in one rule is caching the lastRevert in another variable after each call or putting the assert after each call.

2021-08-25 16:18 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
These are the asserts timing out that we never got a final response on the problem happening. That's why they remained commented.

2021-08-25 16:21 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +            revert4, "Revert rules are not covering all the cases");
I don't have a preference here, whatever you guys think is better.

2021-08-25 16:22 UTC, naszam commented on certora/DssVestSuckable.spec
> +    bool revert5  = e.block.timestamp >= clf && e.block.timestamp >= bgn && e.block.timestamp < fin && tot * (e.block.timestamp - bgn) > max_uint256;
As discussed with Certora team, in the case of dss-vest we have the following scenarios:
- math operations always returns `mathint` so we can check for `> max_uint256` in revert specs for overflow.
- there are cases where we check overflow for EVM-types that are less then `max_uint256` (e.g. `bgn`, `clf`, `fin`, ...) that we declared `uint256` to be able to check overflow with `> max_uint48()` for example.
- ids, where we should check for strictly `== max_uint256` following the check on `create` function.

2021-08-25 16:34 UTC, naszam commented on certora/DssVestMintable.spec
> +}
Good point!
This is what shelly actually recommended [here](https://github.com/makerdao/dss-vest/pull/32#discussion_r670236296).
So, I think we should, in general, catch the `lastReverted` after the function call and name it accordingly (e.g. `rxdReverted`).

2021-08-25 16:41 UTC, naszam commented on certora/DssVestSuckable.spec
> +    bool revert5  = e.block.timestamp >= clf && e.block.timestamp >= bgn && e.block.timestamp < fin && tot * (e.block.timestamp - bgn) > max_uint256;
Done in 194ffef (fix ids revert case).

2021-08-25 16:44 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    TWENTY_YEARS() returns (uint256) envfree
Done.

2021-08-25 16:47 UTC, kmbarry1 commented on certora/DssVestMintable.spec
> +// Verify that wards behave correctly on rely
This one should be `behaves`.

2021-08-25 16:49 UTC, gbalabasquer commented on certora/DssVestMintable.spec
> +// Verify that wards behave correctly on rely
I was meaning more in general but ok, fixed this one for now.

2021-08-25 16:50 UTC, gbalabasquer commented on certora/DssVestMintable.spec
> +}
Well depends on the case. In this case I think I personally prefer to have one `assert` behind each call to not overload with a lot of variables.

2021-08-25 16:52 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +// }
I'd prefer to leave it commented. Would have been better to write this invariant as a regular one instead of a `rule`. Didn't get too deep to see if was possible but I'd prefer to leave it for future reference.

2021-08-25 16:52 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +                           revert4, "Revert rules are not covering all the cases");
Whatever you guys prefer on this one.

2021-08-25 16:54 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    uint256 balanceBefore = dai.balanceOf(usr);
I think this was discussed in the call I missed. I still don't get why the linking is necessary in the `rule` if already being done in the command call. So far only one revert rule and regarding the authority actually needed this extra enforcement.

2021-08-25 16:55 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    // assert(rxd2 <= tot, "rxd got higher than total");
It was left commented due the timeout thing as we never figured it out why was happening.

2021-08-25 16:57 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    uint256 accruedAmt =
I'd personally prefer to leave it as it is.

2021-08-25 16:57 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
I guess if it starts with a variable or function name then it is fine to start with lower case.

2021-08-25 16:58 UTC, gbalabasquer commented on certora/DssVestSuckable.spec
> +    assert(revert5 => lastReverted, "Fin toUint48 cast did not revert");
Other option is put: `The function rely...` or `The variable fin...`

2021-08-30 17:27 UTC, merged