Changes
makerdao/dss-vest pull request #34
Opened 2021-07-21 21:15 UTC by gbalabasquer

Few changes that came up doing the Certora proofs. Tried to keep it the most modular as possible in order to rollback any of them if desired.

2021-07-21 21:27 UTC, naszam commented on src/DssVest.sol
> +        require(ids < uint256(-1),                         "DssVest/id-overflow");
```suggestion
        require(ids < uint256(-1),                         "DssVest/ids-overflow");
```

2021-07-22 15:46 UTC, naszam commented on src/DssVest.sol
> +        return awards[_id].bgn;
`bgn`,`clf` and `fin` getters should return a `uint48` and `tot` and `rxd` getters should return a `uint128` as per `awards`.

2021-07-22 16:51 UTC, naszam commented on src/DssVest.sol
>      */
Should we add error messages for math and cast functions?

2021-07-27 17:16 UTC, gbalabasquer commented on src/DssVest.sol
> +        return awards[_id].bgn;
This is something I'm not 100% sure. We could prefer returning standard `uint256` for everything using these getters.

2021-07-28 11:28 UTC, hexonaut commented on src/DssVest.sol
> +        return awards[_id].bgn;
I think `uint256` is fine, but I don't have strong feelings either way.

2021-07-28 12:05 UTC, naszam commented on src/DssVest.sol
> +        emit Yank(_id, _end);
L414, regarding CVF-38, I think we could consider the following refactoring:
```
constructor(address chainlog_) public DssVest() {
ChainlogLike _chainlog = chainlog = ChainlogLike(chainlog_);
VatLike _vat = vat = VatLike(_chainlog.getAddress("MCD_VAT"));
DaiJoinLike _daiJoin = daiJoin = DaiJoinLike(_chainlog.getAddress("MCD_JOIN_DAI"));
```

2021-07-28 12:19 UTC, naszam commented on src/DssVest.sol
>      }
L261 What if we declare the `valid` function public and use it internally for award validation instead of `_award.usr != address(0)` in `unpaid`, `_yank`, `accrued`?
The condition checked in `valid`, `rxd < tot` should exclude awards that are already paid in full.

2021-07-28 12:26 UTC, gbalabasquer commented on src/DssVest.sol
>      }
I don't think we want to revert in `unpaid` or `accrued` if the award was completed paid.

2021-07-28 13:30 UTC, hexonaut requested changes
Some changes requested.

2021-07-28 13:30 UTC, hexonaut commented on src/DssVest.sol
> +        }
Agree with CVF-32 that we should just revert if the `_end` is greater than or equal to the `_award.fin`.

2021-07-28 13:32 UTC, hexonaut commented on src/DssVest.sol
> +        emit Yank(_id, _end);
Casting doesn't require any extra gas, so it's a bit ugly, but not a big deal imo. Caching the cast on the stack will actually use more gas I believe.

2021-07-28 14:21 UTC, gbalabasquer commented on src/DssVest.sol
>          require(_tot / _tau <= cap,                        "DssVest/rate-too-high");
I was wondering about this one because it is true that in general is better to use a multiplication than a division to avoid rounding errors, but in this case the rounding is not important and the constraint is more explicit in the way it is.
Also, doing the change, the `cap` test starts failing as actually the `cap`s that we define are like a total amount we want per year divided the seconds a year has (which will be the natural way to define this `cap`).
So I think in this specific case makes sense to define the `require` in the same way as you would set the `cap` value.

2021-07-28 14:28 UTC, gbalabasquer commented on src/DssVest.sol
> +        }
I think this was on purpose to avoid a spell fails in case we want to `yank` an award and for some reason the time passes. @brianmcmichael could clarify.

2021-07-28 14:30 UTC, gbalabasquer commented on src/DssVest.sol
>          require(_bgn > sub(block.timestamp, TWENTY_YEARS), "DssVest/bgn-too-long-ago");
I have no problem making this change, but didn't understand the argument of why in the audit. Can you clarify?

2021-07-28 14:51 UTC, brianmcmichael commented on src/DssVest.sol
> +        return awards[_id].bgn;
`uint256` is ok here since they will be easier to manipulate in the calling contract

2021-07-28 14:51 UTC, gbalabasquer commented on src/DssVest.sol
>          require(_award.usr != address(0), "DssVest/invalid-award");
Done.

2021-07-28 14:52 UTC, hexonaut commented on src/DssVest.sol
>          require(_bgn > sub(block.timestamp, TWENTY_YEARS), "DssVest/bgn-too-long-ago");
Timestamps are seconds since 1970. This would underflow if the current date is 1990 or earlier. Obviously this won't happen, but it's just better practise to prefer addition over subtraction with unsigned integers.

2021-07-28 14:53 UTC, gbalabasquer commented on src/DssVest.sol
>          @param _id     The id of the vesting contract
Done.

2021-07-28 14:53 UTC, hexonaut commented on src/DssVest.sol
>          require(_tot / _tau <= cap,                        "DssVest/rate-too-high");
Ok, I don't feel strongly about this so feel free to leave it as-is.

2021-07-28 14:54 UTC, hexonaut commented on src/DssVest.sol
> +        }
Ah okay yes good point.

2021-07-28 14:57 UTC, gbalabasquer commented on src/DssVest.sol
> +        emit Yank(_id, _end);
Yeah to be honest I'm not 100% if will more gas costly (we can check it). But I'd leave it as it is as well.

2021-07-28 15:26 UTC, gbalabasquer commented on src/DssVest.sol
>          require(_bgn > sub(block.timestamp, TWENTY_YEARS), "DssVest/bgn-too-long-ago");
Right, but we have safe sub, that's why I do not get the real issue.
The only reason I'd say to leave it as it is becasue the two `require` are in a more natural way. Like it is pretty clear you are requiring `twenty years ago < _bgn < twenty years in the future`. The other way is a bit trickier to reason about. However if you feel the best practice is more important then I can change it. Not strong sentiment about it.

2021-07-28 15:30 UTC, WilfredTA reviewed
A general thought here about Award struct & the award creation function (called `init` right now).

Although uint48 is large enough to fit the block timestamp + twenty years - and will be large enough for quite some time - I think it is generally not the best to do it this way because:
1. Theoretically, that assumption will break at some point, so it isn't future proof
2. The semantics of `clf` and `tau` parameters in the init function differ from the semantics of the variables of the same name stored in the `Award` struct, which is confusing

Instead, what about this:
1. `bgn`, `clf` and `tau` are changed to uint32's, which is larger than the space required to store the max offset of 20 years.
2. The timestamp of Award registration is stored as a uint256 in the Award struct

This preserves the ability to preregister awards, because `bgn` `clf` and `fin` are offsets from the registration timestamp. The Award struct might look like this (also including changing res to bool) and in this way still uses the same number of storage slots, so there is no penalty in that regard either. 

```
    struct Award {
        address usr; 
        uint32  bgn; 
        uint32  clf;  
        uint32  fin;  
        address mgr;  
        bool res; 
        uint128 tot;
        uint128 rxd; 
        uint256 registered_at ;
    }
```

2021-07-28 15:49 UTC, gbalabasquer commented
> A general thought here about Award struct & the award creation function (called `init` right now).
> 
> Although uint48 is large enough to fit the block timestamp + twenty years - and will be large enough for quite some time - I think it is generally not the best to do it this way because:
> 
> 1. Theoretically, that assumption will break at some point, so it isn't future proof
> 2. The semantics of `clf` and `tau` parameters in the init function differ from the semantics of the variables of the same name stored in the `Award` struct, which is confusing
> 
> Instead, what about this:
> 
> 1. `bgn`, `clf` and `tau` are changed to uint32's, which is larger than the space required to store the max offset of 20 years.
> 2. The timestamp of Award registration is stored as a uint256 in the Award struct
> 
> This preserves the ability to preregister awards, because `bgn` `clf` and `fin` are offsets from the registration timestamp. The Award struct might look like this (also including changing res to bool) and in this way still uses the same number of storage slots, so there is no penalty in that regard either.
> 
> ```
>     struct Award {
>         address usr; 
>         uint32  bgn; 
>         uint32  clf;  
>         uint32  fin;  
>         address mgr;  
>         bool res; 
>         uint128 tot;
>         uint128 rxd; 
>         uint256 registered_at ;
>     }
> ```

Hmmm I think it has been pretty standard to use `uint48` for timestamps even knowing that at a far away future there will be an overflow, which in this function is actually controlled via the `toUint48`. So yes at some point this won't work anymore but won't break either.
On the other hand doing the change would imply changing the logic in several functions that already consider the values calculated. In this contract it is not very important but that would also add extra gas consumption.
Regarding the `clf` naming usage, I agree, it is what I mentioned yesterday. This should be renamed to another thing so we have the same differentiation that we have between `tau` and `fin`.
That's at least my opinion, let's see what the rest says.

2021-07-28 18:24 UTC, WilfredTA commented
> > A general thought here about Award struct & the award creation function (called `init` right now).
> > Although uint48 is large enough to fit the block timestamp + twenty years - and will be large enough for quite some time - I think it is generally not the best to do it this way because:
> > 
> > 1. Theoretically, that assumption will break at some point, so it isn't future proof
> > 2. The semantics of `clf` and `tau` parameters in the init function differ from the semantics of the variables of the same name stored in the `Award` struct, which is confusing
> > 
> > Instead, what about this:
> > 
> > 1. `bgn`, `clf` and `tau` are changed to uint32's, which is larger than the space required to store the max offset of 20 years.
> > 2. The timestamp of Award registration is stored as a uint256 in the Award struct
> > 
> > This preserves the ability to preregister awards, because `bgn` `clf` and `fin` are offsets from the registration timestamp. The Award struct might look like this (also including changing res to bool) and in this way still uses the same number of storage slots, so there is no penalty in that regard either.
> > ```
> >     struct Award {
> >         address usr; 
> >         uint32  bgn; 
> >         uint32  clf;  
> >         uint32  fin;  
> >         address mgr;  
> >         bool res; 
> >         uint128 tot;
> >         uint128 rxd; 
> >         uint256 registered_at ;
> >     }
> > ```
> 
> Hmmm I think it has been pretty standard to use `uint48` for timestamps even knowing that at a far away future there will be an overflow, which in this function is actually controlled via the `toUint48`. So yes at some point this won't work anymore but won't break either.
> On the other hand doing the change would imply changing the logic in several functions that already consider the values calculated. In this contract it is not very important but that would also add extra gas consumption.
> Regarding the `clf` naming usage, I agree, it is what I mentioned yesterday. This should be renamed to another thing so we have the same differentiation that we have between `tau` and `fin`.
> That's at least my opinion, let's see what the rest say.

Yeah, fair point about it being standard practice. In my view, even if it is standard practice I question whether it's best practice since the global state is such an important resource. In terms of the effects of making the change across various functions & business logic, that's pretty compelling reason not to make the change so I agree there.

If we both agree on the `clf` name then at least we can submit that improvement here

2021-07-28 18:24 UTC, brianmcmichael commented on src/DssVest.sol
>          require(_bgn > sub(block.timestamp, TWENTY_YEARS), "DssVest/bgn-too-long-ago");
I think changing this is unnecessary complication.

2021-07-28 19:29 UTC, naszam commented on src/DssVest.sol
> +    event Yank(uint256 indexed id, uint256 end);
```suggestion
    event Yank(uint256 indexed id, uint256 indexed end);
```

2021-07-28 20:23 UTC, brianmcmichael commented on src/DssVest.sol
> +        uint256 res;   // Restricted
This can be a `uint8` and packed into the second slot.

2021-07-28 20:24 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(wards[msg.sender] == 1 || awards[_id].usr == msg.sender, "DssVest/not-authorized");
We can add `require(_award.usr != address(0), "DssVest/invalid-award");` here.

2021-07-28 20:24 UTC, brianmcmichael commented on src/DssVest.sol
> +        require(wards[msg.sender] == 1 || awards[_id].usr == msg.sender, "DssVest/not-authorized");
We can add `require(_award.usr != address(0), "DssVest/invalid-award");` here.

2021-07-28 20:51 UTC, naszam commented on src/DssVest.t.sol
> +
Add test coverage for `tot`

2021-07-28 21:04 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(wards[msg.sender] == 1 || awards[_id].usr == msg.sender, "DssVest/not-authorized");
Done!

2021-07-28 21:04 UTC, gbalabasquer commented on src/DssVest.sol
> +        require(wards[msg.sender] == 1 || awards[_id].usr == msg.sender, "DssVest/not-authorized");
Done!

2021-07-28 21:16 UTC, gbalabasquer commented on src/DssVest.sol
> +        uint256 res;   // Restricted
Done!

2021-07-28 21:57 UTC, brianmcmichael commented on src/DssVest.sol
> +        return awards[_id].usr;
I guess we should consider whether we want to include a require on all of these new view functions that check `usr` is not `address(0)`

2021-07-29 21:16 UTC, naszam approved these changes
LGTM

2021-07-30 00:15 UTC, WilfredTA approved these changes
lgtm

2021-07-30 12:51 UTC, gbalabasquer commented on src/DssVest.t.sol
> +
Forgot to say this was done.

2021-07-30 13:34 UTC, brianmcmichael approved these changes
Looks good, changes discussed on call.

2021-07-30 13:39 UTC, merged